language: objective-c
os: osx
osx_image: xcode7
before_install:
- export LANG=de_DE.UTF-8
- brew update
- npm install -g npm@2.14.5
- npm install -g grunt-cli cordova ionic
#before_script:
#- ./scripts/decrypt-key.sh
#- ./scripts/add-key.sh
script:
- npm install
- ionic platform add ios
- ionic build ios --device --debug
#after_success:
#- ./scripts/package-and-upload.sh
#notifications:
#  hipchat: XXXXX@Your Room
env:
  global:
  - APP_NAME="fingerprint-aio-demo"
